targets:
  $default:
    auto_apply_builders: true
    builders:
      event_dispatcher_builder|buildEventDispatcher:
        options:
          eventDispatcherClassName: 'MyEventDispatcher'
          includePackageDependencies: true
      catalyst_builder|buildServiceProvider:
        options:
          providerClassName: 'DefaultServiceProvider'
          includePackageDependencies: true