name: event_dispatcher_builder_example
description: A simple command-line application.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  catalyst_builder: ^6.0.0-dev.2
  catalyst_builder_contracts: ^2.0.0
  event_dispatcher_builder:
    path: ../

dev_dependencies:
  test: ^1.21.1
  lints: ^6.0.0
  build_runner: ^2.5.0
