name: event_dispatcher_builder_example
description: A simple command-line application.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  catalyst_builder: ^3.5.0
  event_dispatcher_builder:
    path: ../

dev_dependencies:
  test: ^1.21.1
  lints: ^2.1.0
  build_runner: ^2.0.1
