builders:
  preflight:
    import: 'package:event_dispatcher_builder/src/builder/builders.dart'
    builder_factories:
      - 'runPreflight'
    build_extensions: { '.dart': [ '.event_dispatcher_builder.preflight.json' ] }
    build_to: cache
    auto_apply: root_package

  buildEventDispatcher:
    import: 'package:event_dispatcher_builder/src/builder/builders.dart'
    builder_factories:
      - 'buildEventDispatcher'
    build_extensions: { '.dart': [ '.event_dispatcher_builder.g.dart' ] }
    build_to: source
    auto_apply: root_package
    required_inputs:
      - '.event_dispatcher_builder.preflight.json'
    runs_before:
      - catalyst_builder:preflight