name: event_dispatcher_builder
description: A event dispatcher builder for dart. Easy to use and lightweight as a feather.
version: 2.0.0-dev.1
homepage: 'https://www.mintware.de/'
repository: 'https://github.com/mintware-de/event_dispatcher_builder'

environment:
  sdk: ^3.5.0

dependencies:
  code_builder: ^4.0.0
  dart_style: '>=2.3.1 <4.0.0'
  build: ^4.0.0
  glob: ^2.0.0
  analyzer: ^8.0.0

dev_dependencies:
  build_runner: ^2.5.0
  test:
  lints:
